version: '2'

volumes:
  orderer.example.com:
  peer0.lcd.example.com:
  peer0.audio.example.com:
  peer0.cpu.example.com:
  peer0.tv.example.com:
  peer0.pc.example.com:
  peer0.payment.example.com:
  peer0.store.example.com:

services: 
  peer-base:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment: 
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=WARN
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes: 
    - /var/run/:/host/var/run

  orderer:
    container_name: produce-orderer
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment: 
      - FABRIC_LOGGING_SPEC=WARN
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes: 
      - ./channel-artifacts/genesis.block://var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
  
  lcd:
    container_name: material-lcd
    extends: 
      service: peer-base
    environment: 
      - CORE_PEER_ID=lcd.peer0
      - CORE_PEER_ADDRESS=material-lcd:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=material-lcd:7051
      - CORE_PEER_LOCALMSPID=material.lcd
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes: 
      - ./crypto-config/peerOrganizations/lcd.example.com/peers/peer0.lcd.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.lcd.example.com:/var/hyperledger/production
    ports: 
      - 7051:7051
      - 7053:7053

  audio:
    container_name: material-audio
    extends: 
      service: peer-base
    environment: 
      - CORE_PEER_ID=audio.peer0
      - CORE_PEER_ADDRESS=material-audio:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=material-audio:7051
      - CORE_PEER_LOCALMSPID=material.audio
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes: 
      - ./crypto-config/peerOrganizations/audio.example.com/peers/peer0.audio.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.audio.example.com:/var/hyperledger/production
    ports: 
      - 8051:7051
      - 8053:7053

  cpu:
    container_name: material-cpu
    extends: 
      service: peer-base
    environment: 
      - CORE_PEER_ID=cpu.peer0
      - CORE_PEER_ADDRESS=material-cpu:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=material-cpu:7051
      - CORE_PEER_LOCALMSPID=material.cpu
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes: 
      - ./crypto-config/peerOrganizations/cpu.example.com/peers/peer0.cpu.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.cpu.example.com:/var/hyperledger/production
    ports: 
      - 9051:7051
      - 9053:7053

  tv:
    container_name: product-tv
    extends: 
      service: peer-base
    environment: 
      - CORE_PEER_ID=tv.peer0
      - CORE_PEER_ADDRESS=product-tv:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=product-tv:7051
      - CORE_PEER_LOCALMSPID=product.tv
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes: 
      - ./crypto-config/peerOrganizations/tv.example.com/peers/peer0.tv.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.tv.example.com:/var/hyperledger/production
    ports: 
      - 10051:7051
      - 10053:7053

  pc:
    container_name: product-pc
    extends: 
      service: peer-base
    environment: 
      - CORE_PEER_ID=pc.peer0
      - CORE_PEER_ADDRESS=product-pc:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=product-pc:7051
      - CORE_PEER_LOCALMSPID=product.pc
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes: 
      - ./crypto-config/peerOrganizations/pc.example.com/peers/peer0.pc.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.pc.example.com:/var/hyperledger/production
    ports: 
      - 11051:7051
      - 11053:7053

  payment:
    container_name: payment
    extends: 
      service: peer-base
    environment: 
      - CORE_PEER_ID=payment.peer0
      - CORE_PEER_ADDRESS=payment:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=payment:7051
      - CORE_PEER_LOCALMSPID=payment
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes: 
      - ./crypto-config/peerOrganizations/payment.example.com/peers/peer0.payment.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.payment.example.com:/var/hyperledger/production
    ports: 
      - 12051:7051
      - 12053:7053

  store:
    container_name: store
    extends: 
      service: peer-base
    environment: 
      - CORE_PEER_ID=store.peer0
      - CORE_PEER_ADDRESS=store:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=store:7051
      - CORE_PEER_LOCALMSPID=store
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes: 
      - ./crypto-config/peerOrganizations/store.example.com/peers/peer0.store.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.store.example.com:/var/hyperledger/production
    ports: 
      - 13051:7051
      - 13053:7053

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment: 
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=product-tv:7051
      - CORE_PEER_LOCALMSPID=product.tv
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/tv.example.com/users/Admin@tv.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes: 
       - /var/run/:/host/var/run/
       - ../chaincode/:/opt/gopath/src/produce
       - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
       - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
       - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on: 
      - orderer
      - lcd
      - audio
      - cpu
      - tv
      - pc